sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-042
env:
  global:
    -
    # LTD_AWS_ID
      secure: ToBogWZZA2TBS98AAau4PwRxmOjA0sKS4I9vbwkImVlRxJuaLeG1E7MLOgX0Mj1rg2BysFGhWnA1emebVop64DWptScGwG+oeSllg3LU+5LLfCKLVJAj9LC1/sDBKdGS5+Uun3+WM6NtHmnGtJpNf6jiV5w7quC6i4OgIxuzDsK0IkSo/BQWDbGjlEISfcB1UTaU+P23cZPpKjB1Oz9fYtRfk5tk89A2Hp48SKhQS9ZDhGp8Fd2Ya9AiiVhRgfhQGznffu/abU39Pjjypi5pzdUAUWELV+AkGO2oj2+2w4dyQjOWk1MDYp1q4sVH7NwIfT6ZHdJHIkaTCXIglE38fNlVacrqRwgzLJyDI5VR91LIDqnxwU8/qVv4G9FnX95m7pNIMrdSBwvY3dt9+KAz78tGU/kQilfI8Ke9TkJN+HatTBEpcFF7W2/m5jw1I+YWec5pWmSMSJYO1GxlDHWJL1NvV6Vekhwm0H1qXa3WDuvSqCjbDQkJbtQEDLNS4FYCT9FQ1X+ff2xTe91IM79e8SLdV6JTn11QtgB26e66pggdDypAWcNr4nErfBXZ4+jkIAoFHfM+gT1W8R2lJJiSoxHuQizTeskLzxqfNYVmQ97rGb/i+By9haGcEsM5GZ6PUbrfv71+gFiWzVAYRSTgj0J70DlLRaph4UstvwKnEak=
    -
    # LTD_AWS_SECRET
      secure: Zt9h3PHREl6c1F7pbCMJmew2d6QCId9YdhxnFoeuoQ4HQ6FX+hiXWE4c3eaLeldo10ZQx59c3Tzka4CSXq9x5SxqV9VuLwwz8ehczDT810dBlJuoB4kppV8nK7nuF1lmCVhyXddaFVxx/SHfCuhOyse1Z+hVDYzrA92Kll6CU54idJ4hxocwfH7di2rQkMeG0OEd9TIpJ91OyFA+NN89tXL7iQQp2mue8Zh/fbq/26G5Jd8WQSmNWuFKdFViCujDqMohMPnNTRVKmY4iJoEdi1cmgBkNy9CPP1+hQUoRBH1xcmpWVdppPKArOW7m4lE7L8/IJhNSR5NL65pjReNGAT10RzO5rC3gNkWBdWpds8PGiRXqsqMFg2Eu1QtYItApaiIUVRCx4qE7xJ/ul5zymhoDsyEISdPEVi/po4GwjklXQJwcVfgKuvJ2RsvgKZADMTaKg6RiRUVIdyoui5qfmKKWPO9nvq7TXDkhTW4FrgMA/Eh8U7oM192M1UR/oIMSSTROAK++xNTPFLCq749UQKxwyxqONM5lklVNrsZP7YsOL1uHQHMZOkAd5ePdSm9M5CzH2gHwesDnNOL1/8J9pHBm++kT9J9ZnwH4ZtANVYCxeofAjGi9ZAI4yBK4fZkJcNdf3N8biQ5OHMaFS0zQWmwxlFOzY4wwhEv1Pv9/yy0=
    -
    # LTD_USERNAME
      secure: px9wHM8gpVml5aWPWsSSD/X39qzmNDZOrW19s4kEyXWMFGStlYkIwNpq6kctpmTXUopHy7k8vm0/NzLkb0wsw5Xt+9kPNRSoCXczlXSxHXszOtQ50LyQdPK0sn0Td0CR4CpBaoyDiUK2WxHX6LFCbqY1eOAke7fF2ok7uOOwFUBjRAQF+Gai0hrw5e1eZKp1yquVP8PQi0ulPoT4dsCSDMQ1skb7qGtPwyRdVfmpx+1O10iEnRxSAZjRKteomxgnaCluIXgJBiTF/2GvUio0YdpjuKbkYykc9Jx+q2nsUV/kquYWL0YjjoURNKKQNhnmc6uBYvjH0bQBpm1owXTXTDhoCEz8NAOAfUn4/86isqZUEl0PpJu07iweZPJkWdPGdFdsS+Z5xlaX+6kufUTHJaVclXVnHjf3bpLD4N20yoahglYWUBdiz9O0e5/9BZSrkMTMq6MtuZTJA4LKgPv2k/4gIaIr9eVZ3ukNjcbFLS/bxJR6AM0BKBTAuFoSIYkRyDJDR9h5A0bDCudOjHK9x8CeVaH6oRlrnYF9XNLik3qsRCM7stuRCI+ygdUgmfc4QwjdYUPm4ICKhe07ijIVOZbqEmBg3+MLf+PR9odIyRCB/S0QpoTnea5Ag48g6ZjSSbktZqk1qi2Z/aJVCzTtGTgmoF2W+OBBtw8CGqIkP0I=
    -
    # LTD_PASSWORD
      secure: MNV3Hmim7Ds5onkqqPUIPrdTnM/I5JQCB73jtnYuRIhD5Uxz1Mg6eFYvBItGpG7F0fpgc3Q/UneR0qI3yE43I6GqLaRIK3RHdGen4o0GYcGvVHOIyN0xKqhwFB7ghnwjKfWduBoNjFTjSy9GRr+QGN7bK4wBOo8Mho3eitrqmfUzmSiYDJuwbRNIOjJQkq1SWCkVa5pHcyaljLdVZB0MqxzxhXSYn828+rYUMex5ZQo78VMdRVanr5o/VqVjhEQsuImOO1yWr30l6x+LBWdlDYaoMtypSNVnIqSULcEdyTBKOTJvSVXQT5/i+H+CR5VhTlfyz4d9K5D3xazc+V7pllZEFcQNe7S1JEzdqsFsJofOJ6La4Lp5S61Xf5lnktJPsmWhFYTg66MEn9pJ7Tn74ntEux7VKWaWuYBKc9ynrClBS6D2tEgitqVErAIeGve/MZ2SJXWYdHqZeFIc/fL4/ZpOdfOur3OFrt6/aU/j+jtWNFPcpavD1/aed/33C+YStYROdZGNV9c66ku9sn6ppqlfIzlFqPfPeQCxqmwhsTRm61qJKhtC21eBR70LfDqNex2Bd15/Lg+V5qBhTyxQPVeRXM9Wk2sG/vFOPKH6bOa36i45qJQdckhTsD3bZZj7wWEhiRI5Mb+MHJkv/CcV5hPlUIVDDRYlZokGcZ30ymQ=
